[package]
name = "cef_ffi"
version = "0.1.0"
authors = ["anderejd <rajder@gmail.com>"]
build = "build.rs"

[dependencies]

[build-dependencies]
# TODO: Specify dependency versions when cef-rs is stable.
bindgen = "*"

